---

# Hostname.  Start with ttn-ORG
hostname: ttn-org-example

# Define this to use an ssh tunnel.  Leave undefined or set to '0' to
# disable ssh tunnel.
# ssh_tunnel_remote_port: 15022
# Define the keepalive port, must also be unique per gateway
# ssh_tunnel_keepalive_base_port: 10084

# Actual address or hostname of the gateway.  This can be a hostname
# or IP address.
ansible_host: hostname.example.com
ansible_port: 22

# Uncomment the following to force network configuration to DHCP (this
# is the default config )
# eth0_type: dhcp
# Uncomment and set the following info to set a static address
#eth0_type: static
#eth0_address: 10.0.0.51
#eth0_netmask: 255.255.255.0
#eth0_gateway: 10.0.0.1
# By default we'll configure google nameservers, if you want to
# specify, use:
#static_domain:   example.com
#static_nameservers:
#  - 192.168.1.4
#  - 192.168.1.5

# To configure wireless the following setup is required.  Wireless
# LANs usually use DHCP, but you can provide a static address in the
# same format as for an Ethernet interface.  Make sure that the
# wireless interface you have is supported by mLinux.
#eth0_type: manual
#wlan0_type: dhcp
# Wireless keys should not be stored here, but in a vault in this format
# For WPA-PSK and WPA-PSK2:
#wireless_keys: { ssid: 'MYNETWORKNAME', psk: 'ASecretPhrase' }
# For (very insecure) WEP and plain text
#wireless_keys: { ssid: 'MYNETWORKNAME', psk: 'TotallyInsecure', key_mgmt: 'NONE' }

# To upgrade to a specific version of mLinux, specify it here.
# It's best to do this when you are on the same network, or have
# serial console access to the gateway
# mlinux_version 3.3.7

# Descriptive location of the gateway
description: Test node in Org

# Location can be set and will be used as "fake" GPS data if the GPS
# card is not being used.
# use -1 for altitude if not known.
latitude: 42.55555
longitude: -76.55555
altitude: -1
# Use the GPS if present.  This requires an external antenna
# use_gps: true
