---

# Hostname.  Start with ttn-ORG
hostname: ttn-org-example2

# Define this to use an ssh tunnel.  Leave undefined or set to '0' to
# disable ssh tunnel.
ssh_tunnel_remote_port: 15023

# Actual address or hostname of the gateway.  This can be a hostname
# or IP address.
ansible_host: hostname3.example.com
ansible_port: 22

# Uncomment the following to force network configuration to DHCP (this
# is the default config )
# eth0_type: dhcp
# Uncomment and set the following info to set a static address
# eth0_type: static
## eth0_address: 10.0.0.51
## eth0_netmask: 255.255.255.0
## eth0_gateway: 10.0.0.1
# By default we'll configure google nameservers, if you want to
# specify, use:
## static_domain:   example.com
## static_nameservers:
#  - 192.168.1.4
#  - 192.168.1.5

# To configure wireless the following setup is required.  Wireless
# LANs usually use DHCP, but you can provide a static address in the
# same format as for an Ethernet interface.  Make sure that the
# wireless interface you have is supported by mLinux.
## eth0_type: manual
## wlan0_type: dhcp
# Wireless keys should not be stored here, but in a vault in this format
# For WPA-PSK and WPA-PSK2:
## wireless_keys: { ssid: 'MYNETWORKNAME', psk: 'ASecretPhrase' }
# For (very insecure) WEP and plain text
## wireless_keys: { ssid: 'MYNETWORKNAME', psk: 'TotallyInsecure', key_mgmt: 'NONE' }

# To upgrade to a specific version of mLinux, specify it here.
# It's best to do this when you are on the same network, or have
# serial console access to the gateway
# mlinux_version 3.3.7

# Descriptive location of the gateway
description: Production node in Org

# Location, use -1 for altitude if not known.
latitude: 43.55555
longitude: -76.55555
altitude: -1
